#!/bin/bash

COMMIT_MSG_FILE=$1
MESSAGE=$(cat "$COMMIT_MSG_FILE")

# Игнорируем ВСЕ системные коммиты
if echo "$MESSAGE" | grep -qE "^(Merge (pull request #|branch|remote-tracking|commit)|Revert )"; then
  exit 0
fi

# Проверяем первую строку
if ! echo "$MESSAGE" | grep -qE "^#[0-9]+ (feat|fix|docs|style|refac|test|chore|perf)(\([a-z]+\))?: .+"; then
  echo "❌ Коммит должен иметь структуру в lower-case: #[task-number] type[(scope)]: description"
  echo "Где type один из: feat, fix, docs, style, refac, test, chore, perf"
  echo "Примеры:"
  echo "  #1 feat: add login form"
  echo "  #1 feat(auth): add login form" 
  echo "  #1 fix: correct calculation"
  exit 1
fi
